/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.radiorecorder;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.app.Activity;

@Kroll.module(name = "Radiorecorder", id = "de.appwerft.radiorecorder")
public class RadiorecorderModule extends KrollModule {

	private static final String LCAT = "RR 📻";

	public RadiorecorderModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
	}

	@Override
	public void onStart(Activity activity) {
		String rootActivityClassName = TiApplication.getInstance()
				.getApplicationContext().getPackageName()
				+ "."
				+ TiApplication.getAppRootOrCurrentActivity().getClass()
						.getSimpleName();
		Log.d(LCAT, "onStart rootActivityClassName = " + rootActivityClassName);

		super.onStart(activity);
	}

	@Override
	public void onPause(Activity activity) {
		String activityClassName = TiApplication.getInstance()
				.getApplicationContext().getPackageName()
				+ "."
				+ TiApplication.getAppCurrentActivity().getClass()
						.getSimpleName();
		super.onPause(activity);
	}
}
